"""Main module."""
import Adafruit_DHT # https://github.com/adafruit/Adafruit_Python_DHT

def temperature_humidity():
    """
    Returns
        humidity    float
                    humidity data generated by AM2301
        temperature float
                    temperature data in celsius generated by AM2301
    """
    humidity, temperature = Adafruit_DHT.read_retry(sensor, pin)
    if humidity is not None:
        humidity = round(humidity, 1)
    else:
        pass
    if temperature is not None:
        temperature = round(temperature, 1)
    else:
        pass

    return humidity, temperature

pin = 21 # GPIO21 aka Pin 40
sensor = Adafruit_DHT.AM2302 

if __name__ == '__main__':
    humidity, temperature = temperature_humidity()
    print('Humidity:\t{}%'.format(humidity))
    print('Temperature:\t{}c'.format(temperature))
