"""Main module."""

import Adafruit_DHT # https://github.com/adafruit/Adafruit_Python_DHT
from time import sleep

def temperature_humidity(gpio_pin):
    """
    Uses an AM2301 sensor to get ambient temperature and humidity.

    Parameters
        gpio_pin        int
                        The GPIO pin the AM2301 is connected to.
    Returns
        humidity        float
                        humidity data generated by AM2301
        temp_celsius    float
                        temperature data in celsius generated by AM2301
    """

    sensor = Adafruit_DHT.AM2302

    successful_reading = False

    while successful_reading is False:
        humidity, temp_celsius = Adafruit_DHT.read_retry(sensor, gpio_pin)
        if humidity is None:
            print(f"Humidity sensor returning {humidity}, Trying again...")
            sleep(1)
        elif humidity > 100 or humidity < 0:
            print(f"Humidity sensor returning {humidity}% humidity. Trying again...")
            sleep(1)
        else:
            successful_reading = True

    # humidity, temp_celsius = Adafruit_DHT.read_retry(sensor, gpio_pin)

    humidity = round(humidity, 1)
    temp_celsius = round(temp_celsius, 1)

    return temp_celsius, humidity

gpio_pin = 4 # GPIO4 aka Pin 7

if __name__ == '__main__':
    temp_celsius, humidity = temperature_humidity(gpio_pin=gpio_pin)
    print('Humidity:\t{}%'.format(humidity))
    print('Celsius:\t{}c'.format(temp_celsius))
